export const SAVE_CONTACT = 'SAVE_CONTACT';
export const FILL_CONTACTS = 'FILL_CONTACTS';
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';