import React from "react";
import Head from "next/head";
import Container from '@mui/material/Container';
import Header from "../components/Header";

export interface ILayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<ILayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Pagina Principal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container maxWidth="sm">{children}</Container>
    </>
  );
};

export default Layout;
